# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import rendering_service_pb2 as rendering__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in rendering_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RenderingServiceStub(object):
    """The rendering service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RenderFrame = channel.unary_unary(
                '/rendering.RenderingService/RenderFrame',
                request_serializer=rendering__service__pb2.RenderRequest.SerializeToString,
                response_deserializer=rendering__service__pb2.RenderResponse.FromString,
                _registered_method=True)
        self.StreamFrames = channel.stream_stream(
                '/rendering.RenderingService/StreamFrames',
                request_serializer=rendering__service__pb2.RenderRequest.SerializeToString,
                response_deserializer=rendering__service__pb2.RenderResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/rendering.RenderingService/HealthCheck',
                request_serializer=rendering__service__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=rendering__service__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.GetStats = channel.unary_unary(
                '/rendering.RenderingService/GetStats',
                request_serializer=rendering__service__pb2.StatsRequest.SerializeToString,
                response_deserializer=rendering__service__pb2.StatsResponse.FromString,
                _registered_method=True)


class RenderingServiceServicer(object):
    """The rendering service definition
    """

    def RenderFrame(self, request, context):
        """Render a single frame with given parameters
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamFrames(self, request_iterator, context):
        """Stream multiple frames continuously
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check for replica management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStats(self, request, context):
        """Get current rendering statistics
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RenderingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RenderFrame': grpc.unary_unary_rpc_method_handler(
                    servicer.RenderFrame,
                    request_deserializer=rendering__service__pb2.RenderRequest.FromString,
                    response_serializer=rendering__service__pb2.RenderResponse.SerializeToString,
            ),
            'StreamFrames': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamFrames,
                    request_deserializer=rendering__service__pb2.RenderRequest.FromString,
                    response_serializer=rendering__service__pb2.RenderResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=rendering__service__pb2.HealthCheckRequest.FromString,
                    response_serializer=rendering__service__pb2.HealthCheckResponse.SerializeToString,
            ),
            'GetStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStats,
                    request_deserializer=rendering__service__pb2.StatsRequest.FromString,
                    response_serializer=rendering__service__pb2.StatsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rendering.RenderingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rendering.RenderingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RenderingService(object):
    """The rendering service definition
    """

    @staticmethod
    def RenderFrame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(  # type: ignore[attr-defined]
            request,
            target,
            '/rendering.RenderingService/RenderFrame',
            rendering__service__pb2.RenderRequest.SerializeToString,
            rendering__service__pb2.RenderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamFrames(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(  # type: ignore[attr-defined]
            request_iterator,
            target,
            '/rendering.RenderingService/StreamFrames',
            rendering__service__pb2.RenderRequest.SerializeToString,
            rendering__service__pb2.RenderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(  # type: ignore[attr-defined]
            request,
            target,
            '/rendering.RenderingService/HealthCheck',
            rendering__service__pb2.HealthCheckRequest.SerializeToString,
            rendering__service__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(  # type: ignore[attr-defined]
            request,
            target,
            '/rendering.RenderingService/GetStats',
            rendering__service__pb2.StatsRequest.SerializeToString,
            rendering__service__pb2.StatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
